Project.toml
src/ADTypes.jl
test/runtests.jl

Maybe it would be reasonable to add a type for FiniteDifferences as well?
A bit inconsistent, in contrast to #10 in this PR I opted for a default value of `nothing` since I wanted to avoid pulling in FiniteDifferences which has much more dependencies than EnzymeCore. Alternatively, on Julia >= 1.9 one could add a weak dependency on FiniteDifferences and define a constructor with a more concrete default value such as `FiniteDifferences.central_fdm(5, 1)` (but this would lead to inconsistencies between Julia < 1.9 and >= 1.9...).

Add AD type for FiniteDifferences

---

Project.toml
src/ADTypes.jl
test/runtests.jl

Fixes #9 and adds more tests.
I chose to not introduce any new types but instead added a field to `AutoEnzyme` (and hence an additional type parameter which makes the PR technically breaking but I'm not sure how widespread the use of `AutoEnzyme` is within the community and if there are any examples that would actually break?). The advantage is that one could even specify other modes than `Enzyme.Forward` and `Enzyme.Reverse` such as `Enzyme.ReverseWithPrimal`.
Since I set the default value to `EnzymeCore.Reverse`, a dependency on `EnzymeCore` is added. Even though it is lightweight (only depends on Adapt and I'm about to open a PR that would make it a weak dependency on Julia >= 1.9, so if accepted the package would have zero dependencies on Julia >= 1.9) this might not be desirable. An …

Support Enzyme forward + reverse mode

---

Project.toml
src/ADTypes.jl
test/runtests.jl

Sometimes it can be desirable to use custom ForwardDiff tags: https://www.stochasticlifestyle.com/improved-forwarddiff-jl-stacktraces-with-package-tags/
This is done e.g. in Turing and OrdinaryDiffEq and supported by LogDensityProblemsAD.

Add support for custom tags to ForwardDiff types

---

.github/workflows/CI.yml
src/ADTypes.jl
test/runtests.jl

https://docs.julialang.org/en/v1/base/base/#Base.@kwdef

Use `Base.@kwdef`

---

Project.toml

We did it for CI in #13, but `compat` should be updated too.

Drop support for Julia < 1.6

---

Project.toml
src/ADTypes.jl
test/runtests.jl

This PR adds an `AutoChainRules` AD type. It is built from a `RuleConfig` to allow calling back into AD with `frule_via_ad` or `rrule_via_ad` (see https://juliadiff.org/ChainRulesCore.jl/stable/rule_author/superpowers/ruleconfig.html).
It does not inherit from `AbstractForwardMode` or `AbstractReverseMode` because it can be both.
A similar pattern was used in AbstractDifferentiation.jl
https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/2bc18d07eb5038c997a7f9253bc3f1457124710e/src/backends.jl#L64-L66

Add AutoChainRules(ruleconfig)

---

README.md
src/ADTypes.jl

I'm not sure whether the lack of documentation is a bug or a feature. This is a pretty young and experimental package, so arguably we don't want to expose too much of the internals.
On the other hand it already has [18 registered direct dependents](https://juliahub.com/ui/Packages/General/ADTypes) and 492 indirect ones. I would assume those dependents use "the code as the documentation", which means everything is API by default. This PR makes the API more explicit and discoverable.

Add docstrings and list of exports

---

Project.toml
README.md
src/ADTypes.jl

- Add docstring to `AutoChainRules`
- Add `AutoChainRules` to README

Document AutoChainRules

---

.github/workflows/Documentation.yml
.gitignore
README.md
docs/Project.toml
docs/make.jl
docs/src/index.md

- Add `docs` folder with `make.jl` and `src`
- Put the public and private API reference in `src/index.md`
- Add `Documentation.yml` workflow taken from https://documenter.juliadocs.org/dev/man/hosting/#GitHub-Actions
- Revamp README
- Add badges to README
I have also configured the SSH deploy keys in the repo with DocumenterTools, as described in https://documenter.juliadocs.org/dev/man/hosting/#travis-ssh

Add docs website and revamp README

---

README.md
src/ADTypes.jl
test/runtests.jl

Fix #27
I asked the developer of Diffractor.jl and she said no specific fields or type parameters were needed in the struct

Add AutoDiffractor

---

.github/workflows/TagBot.yml

Workflow file taken from https://github.com/JuliaRegistries/TagBot?tab=readme-ov-file#setup
Since `GITHUB_TOKEN` is read-only by default on ADTypes.jl, it is necessary to elevate its permissions so that it can write in the repo contents (tags)

Update TagBot workflow with write permissions

---

src/ADTypes.jl
test/runtests.jl

[FastDifferentiation.jl](https://github.com/brianguenter/FastDifferentiation.jl) is an efficient symbolic backend which DifferentiationInterface.jl can use
cc @brianguenter, do you think there should be other parameters here to specify how the backend is configured? similar to e.g. chunk size in ForwardDiff or compiled mode toggle in ReverseDiff

Support FastDifferentiation.jl

---

src/ADTypes.jl
test/runtests.jl

We need this patch to be able to use something like:
```julia
DifferentiationInterface.jacobian.(x -> Lux.apply(nns, x, ps), AutoZygote(), eachcol(r))
```

Support dot broadcast

---

docs/src/index.md
src/sparse.jl
test/runtests.jl
test/sparse.jl

Hessian coloring is slightly different from Jacobian coloring, so it needs a dedicated function `symmetric_coloring`, which this PR introduces.
Now we have all we need to implement problems P1 and P2 of the reference paper [_What color is your Jacobian?_](https://epubs.siam.org/doi/10.1137/S0036144504444711) (see tables below). The actual coloring algorithm will vary between `column_coloring/row_coloring` and `symmetric_coloring`, but that's okay: we can subtype `AbstractColoringAlgorithm` as follows
```julia
struct GreedyColoringAlgorithm <: AbstractColoringAlgorithm
vertex_ordering_function::Function  # for instance largest degree first
end
```
and then dispatch
```julia
column_coloring(M, ::GreedyColoringAlgorithm) = # greedy distance-2 coloring
row_coloring(M, …
```

Add symmetric coloring function

---

.github/workflows/CI.yml
Project.toml

The compat bounds for ChainRulesCore and EnzymeCore were the most recent ones. I relaxed them to versions where I am sure that the necessary objects already exist, and added a downgrade compat test on Julia 1.10

Lower compat bounds and downgrade tests

---

.github/workflows/CI.yml
Project.toml
test/runtests.jl

This PR makes EnzymeCoreExt and ChainRulesExt unconditional dependencies for Julia <1.9, thus allowing support for older Julia versions.
We initially decided against it in https://github.com/SciML/ADTypes.jl/pull/40#issuecomment-2055319884, but as shown by #47 some users would like this feature. It is zero-cost for us, so why not?

Support Julia 1.6 (again)

---

.github/workflows/CI.yml
Project.toml
src/ADTypes.jl
test/runtests.jl

Reverts SciML/ADTypes.jl#48
If @ChrisRackauckas says SciML is ready to drop Julia below 1.10, then let's lean into it

Revert "Support Julia 1.6 (again)"

---

.github/workflows/Documentation.yml

Update the workflows in this repository to use SciML's reusable workflows.
This is part of a larger effort to standardise the SciML's CI workflows for more generic and common requirements, to keep the workflows uniform and easier to maintain.

ci: standardise workflows using SciML's reusable workflows

---

src/ADTypes.jl
src/legacy.jl
test/legacy.jl

Add any other context about the problem here.

Add AutoModelingToolkit to deprecations

---

.github/workflows/CI.yml
Project.toml
src/ADTypes.jl
test/runtests.jl

Judging by the discussion with @devmotion in https://github.com/tpapp/LogDensityProblemsAD.jl/pull/29#discussion_r1586798822, support for 1.6 is important in other parts of the ecosystem, even though SciML is willing to drop it sooner. The maintenance burden is very minimal in ADTypes.jl, so I'm adding it again.
Related discussions:
- https://github.com/SciML/ADTypes.jl/pull/40#issuecomment-2056572382
- https://github.com/SciML/ADTypes.jl/pull/48#issuecomment-2078489971

Support Julia 1.6 for Turing and others

---

src/dense.jl

Addresses issues brought up in #31 and [on Slack](https://julialang.slack.com/archives/C6G240ENA/p1715354117347669?thread_ts=1715350423.420429&cid=C6G240ENA).
Reasons for the addition of the *"Exported from ADTypes.jl"* string:
- ADTypes are user-facing
- ADTypes are re-exported by most packages using them
- users might not be aware of `parentmodule` (see links above)

Improve backend type docstrings

---

Project.toml
src/dense.jl
test/dense.jl

Tapir.jl now has a "safe mode", in which lots of additional type checking is performed, in addition to some value checks. I would like to enable it by default (I'll be adding `@info` calls on the Tapir end to make it clear to users that they're using safe mode). This is to ensure that users are aware of this feature, which often makes debugging a lot easier, and can pick up on issues before they propagate to some arbitrary point further on in the code.
Provided that people are happy with this, if someone could advise on the appropriate version bump for this package I would …

Add safe mode

---

Project.toml
src/dense.jl

Fix #56 by reinstating full docstrings with type parameters and fields

Restore full API in docstrings

---

Project.toml
docs/src/index.md
src/ADTypes.jl
src/symbols.jl
test/runtests.jl
test/symbols.jl

In https://github.com/gdalle/DifferentiationInterface.jl/issues/319, @MilesCranmer proposed a mapping from package `Symbol`s to `AbstractADType`s. While this mapping is not strictly necessary, it makes things easier for interfacing with Python. Here's an experimental PR doing just that, let's see what people think.
>[!WARNING]
>I don't want to encourage the use of `Symbol`s, since ADTypes.jl is precisely there to avoid their shortcomings. Hence the strongly-worded docstring.

Add Symbol -> AbstractADType mapping

---

Project.toml
src/ADTypes.jl
src/dense.jl
src/symbols.jl
test/dense.jl

Needed for things like https://github.com/LuxDL/Lux.jl/issues/642 where the return type needs to rely on whether the compiled tape needs to be returned.

Promote ReverseDiff compile field to type

---

Project.toml
src/dense.jl
src/sparse.jl
test/misc.jl
test/runtests.jl

Right now every backend type is printed with its type parameters, which yields very long strings (especially with `AutoSparse`). Since I use those strings in DifferentiationInterface (e.g. as `@testset` names), I figured it would be nice to make them more user-friendly.

Pretty printing

---

Project.toml
src/dense.jl
src/legacy.jl
src/sparse.jl
test/legacy.jl
test/misc.jl

Fix #65 and #66 
Should we test the round-trip-ability of these printings by parsing the string back into an object?

Fix pretty printing and ReverseDiff constructor

---

src/dense.jl
test/dense.jl

Complete #63 by documenting the type parameter, making it part of the API

Document new type parameter for AutoReverseDiff

---

src/legacy.jl
test/legacy.jl

Add any other context about the problem here.

Add deprecated non-kwarg AutoSparseReverseDiff constructor

---

Project.toml
src/dense.jl
test/dense.jl
test/misc.jl

This PR adds a keyword argument (and type parameter) to `AutoEnzyme`, which specified whether the function itself should be considered constant during differentiation. See <https://github.com/SciML/SciMLBenchmarks.jl/pull/988#issuecomment-2228969526> for the related discussion with @wsmoses and @ChrisRackauckas

Add constant_function kwarg to AutoEnzyme

---

Project.toml
src/dense.jl

There was a typo in #72 for the docstring, I switched `true` and `false` in the explanation of `constant_function`

Fix AutoEnzyme docstring for constant_function

---

Project.toml
src/dense.jl
test/dense.jl

> [!WARNING]
> This PR and the associated release are breaking wrt 1.6.1, but we will yank 1.6.1 and 1.6.0 right after
Following a long discussion with @ChrisRackauckas and @wsmoses, we decided to remove the `constant_function` setting for now, and reinsert it later with different defaults (once Enzyme implements a few changes on their side). This PR does the removal and bumps ADTypes to v1.6.2, after which we will need to yank v1.6.0 and v1.6.1.
- https://github.com/EnzymeAD/Enzyme.jl/issues/1669

Remove `constant_function` for `AutoEnzyme`

---

Project.toml
src/dense.jl
test/dense.jl
test/misc.jl

This PR adds a type parameter `A` to `AutoEnzyme` and a keyword argument `function_annotation::Type{A}` to its constructor.
It is the second attempt at properly solving the following issues:
- https://github.com/EnzymeAD/Enzyme.jl/issues/1669
- https://github.com/gdalle/DifferentiationInterface.jl/issues/339

Add `function_annotation` to `AutoEnzyme`

---

Project.toml
src/sparse.jl

- Remove pointer to SparseDiffTools from the docstring of the `AbstractColoringAlgorithm` type, because SparseDiffTools does not implement it (even though it has some of the underlying algortihms)
- Bump version to v1.7.1

Remove mention of SparseDiffTools in AbstractColoringAlgorithm

---

docs/src/index.md
src/sparse.jl
test/runtests.jl
test/sparse.jl

Adds `KnownJacobianSparsityDetector` and `KnownHessianSparsityDetector`, closing #80.

Add `KnownJacobianSparsityDetector` and `KnownHessianSparsityDetector`

---

Project.toml
src/dense.jl
test/dense.jl

Fixes #101 
Adds the relstep and absstep parameters from the FiniteDiff [API](https://docs.sciml.ai/FiniteDiff/stable/api/)

Add the relstep and absstep parameters to AutoFiniteDiff

---

Project.toml
src/dense.jl

#102 added the `relstep` and `absstep` parameters without type annotations, which is equivalent to `::Any`. This PR fixes it.

fix: add type annotation to step parameters in AutoFiniteDiff

---

Project.toml
src/sparse.jl
test/sparse.jl

Adds a natural default `dense_ad(ad::AbstractADType) = ad` to help avoid the following pattern:
```julia
if ad isa AutoSparse
dense_ad(ad)
else
ad
end
```

feat: make `dense_ad` act as the identity on a dense backend

---

Project.toml
src/dense.jl
test/dense.jl

Allow calling `AutoMooncake()` without the `config` keyword

---

Project.toml
docs/src/index.md
src/ADTypes.jl
src/dense.jl
src/symbols.jl
test/dense.jl
test/symbols.jl

Add any other context about the problem here.

Add NoAutoDiff
